const List<String> kNeighborhoods = [
  'Chatuchak',
  'Silom',
  'Lat Phrao',
  'Ari',
  'Thonglor',
  'Bang Na',
  'Ladkrabang',
  'Ratchada',
  'On Nut',
  'Phra Nakhon',
  'Bangrak',
  'Huai Khwang',
  'Bang Kapi',
  'Don Mueang',
  'Nong Khaem',
];
